version: '3.5'
services:
    #Nginx Service
    tours-nginx:
        image: nginx:alpine
        build:
            context: ./docker/nginx/
            dockerfile: ./Dockerfile
        container_name: tours-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./backend:/var/www/backend:ro,default
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - tours-backend
        ports:
            - "8088:80"
            - "4433:443"
        networks:
            - tours-network

    #PHP Laravel Service
    tours-backend:
        image: vokirtim/tours-backend
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        container_name: tours-backend
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: tours-backend
            SERVICE_TAGS: dev
        depends_on:
            - mongodb
        volumes:
            - ./backend/app/:/var/www/backend/app
            - ./backend/routes/:/var/www/backend/routes
            - ./backend/.env:/var/www/backend/.env.production
        networks:
            - tours-network

    #mongo
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        volumes:
          - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh  # mongo < 6
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        networks:
            - tours-network

    tours-frontend:
        container_name: tours-frontend
        image: vokirtim/tours-frontend
        build:
          context: ./frontend
          dockerfile: ./Dockerfile
        volumes:
          - /node_modules
        restart: unless-stopped
        env_file:
          - ./frontend/.env.production
        networks:
            - tours-network

    mongodb-seed:
        image: mongo
        links:
            - mongodb
        volumes:
            - ./db/mongo-seed:/mongo-seed
        command:
            /mongo-seed/import.sh
        networks:
            - tours-network

    tours-django:
        image: vokirtim/tours-django
        restart: always
        command: python manage.py runserver 0.0.0.0:9292
        volumes:
            - ./ml:/code
        build:
            context: ./ml/
            dockerfile: ./Dockerfile
        depends_on:
            - mongodb
        ports:
            - '9292:9292'
        networks:
            - tours-network

networks:
    tours-network:
        driver: bridge
