# Generated by Django 3.2.19 on 2023-05-16 03:13

from django.db import migrations, models
from django.core.management import call_command


def import_data():
    call_command('loaddata', '../data/data.json', verbosity=2)


def reverse_func(apps, schema_editor):
    print('reverse')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data', models.CharField(max_length=60)),
            ],
        ),

        migrations.RunPython(import_data, reverse_func, elidable=False)
    ]
